project_id = "ralgnulxknrougtcmyug"

[functions.openai-tts]
verify_jwt = false

[functions.product-chat]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false
